// N Chedurov All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace ProjectNGameplayTags
{
	/**** Input Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	
	/**** Inventory Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_Equip)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_UnEquip)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_Drop)

	/**** Message Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Potion)

	/**** Attributes Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Strength)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Intelligence)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Dexterity)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Vitality)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Health)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxHealth)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Mana)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxMana)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Stamina)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxStamina)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Poise)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxPoise)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MovementSpeed)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Armor)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Evasion)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ArmorPenetration)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitChance)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitDamage)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_HealRegeneration)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ManaRegeneration)
}
