// N Chedurov All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace ProjectNGameplayTags
{
	/**** Input Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Esc)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interaction)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Inventory)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_RMB)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LMB)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Alt)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Crouch)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Map)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot1)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot2)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot3)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot4)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot5)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot6)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot7)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot8)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot9)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot0)
	
	/**** Inventory Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_Equip)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_UnEquip)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InventoryTag_Drop)

	/**** Item Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Dagger)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Sword)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_GreatSword)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Bow)

	/**** Message Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Potion)

	/**** Attributes Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Strength)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Intelligence)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Dexterity)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Vitality)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Health)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxHealth)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Mana)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxMana)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Stamina)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxStamina)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Poise)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxPoise)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MovementSpeed)
	
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Armor)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Evasion)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ArmorPenetration)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitChance)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitDamage)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_HealRegeneration)
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ManaRegeneration)

	/**** Event Tags ****/
	PROJECTN_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_SpawnEffect)
}
